In [4]:
import pandas as pd

df = pd.read_csv("C:\\Users\\nnish\\OneDrive\\Desktop\\customer_purchase_dataset.xls")

df.head()

,Customer_ID,Age,Gender,City,Income,Website_Visits,Previous_Purchases,Membership_Level,Purchased
0,1,22,Female,Toronto,30000.0,2,0,Basic,No
1,2,25,Male,Oshawa,35000.0,3,0,Basic,No
2,3,47,Female,Toronto,72000.0,10,3,Gold,Yes
3,4,52,Male,Ajax,85000.0,14,4,Gold,Yes
4,5,46,Female,Whitby,68000.0,9,2,Silver,Yes

In [5]:
# Step 2: Inspecting the Dataset

# Display the first 5 rows of the dataset to get a quick overview
df.head()

,Customer_ID,Age,Gender,City,Income,Website_Visits,Previous_Purchases,Membership_Level,Purchased
0,1,22,Female,Toronto,30000.0,2,0,Basic,No
1,2,25,Male,Oshawa,35000.0,3,0,Basic,No
2,3,47,Female,Toronto,72000.0,10,3,Gold,Yes
3,4,52,Male,Ajax,85000.0,14,4,Gold,Yes
4,5,46,Female,Whitby,68000.0,9,2,Silver,Yes

In [6]:
# Show the number of rows and columns in the dataset
df.shape

(51, 9)

In [7]:
# Display the names of all columns in the dataset
df.columns

Index(['Customer_ID', 'Age', 'Gender', 'City', 'Income', 'Website_Visits',
       'Previous_Purchases', 'Membership_Level', 'Purchased'],
      dtype='object')

In [8]:
# Show general information about the dataset
# This includes column names, non-null values, and data types
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51 entries, 0 to 50
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Customer_ID         51 non-null     int64
 1   Age                 51 non-null     int64
 2   Gender              51 non-null     object
 3   City                50 non-null     object
 4   Income              50 non-null     float64
 5   Website_Visits      51 non-null     int64
 6   Previous_Purchases  51 non-null     int64
 7   Membership_Level    50 non-null     object
 8   Purchased           51 non-null     object
dtypes: float64(1), int64(4), object(4)
memory usage: 3.7+ KB

In [9]:
# Display the data type of each column
df.dtypes

Customer_ID             int64
Age                     int64
Gender                 object
City                   object
Income                float64
Website_Visits          int64
Previous_Purchases      int64
Membership_Level       object
Purchased              object
dtype: object

In [10]:
# Step 3: Understanding the Problem

# Business problem:
# The company wants to understand which customers are more likely to buy a product.
business_problem = "A company wants to predict which customers are likely to purchase a product."

# Machine learning problem:
# Since the target variable has two possible classes, Yes or No, this is a classification problem.
ml_problem = "This is a classification problem because we want to predict whether the customer will purchase or not."

# Prediction goal:
# The goal is to predict the value of the target column called 'Purchased'.
prediction_goal = "Predict whether a customer will purchase a product: Yes or No."

# Display the problem definition
print("Business Problem:")
print(business_problem)

print("\nMachine Learning Problem:")
print(ml_problem)

print("\nPrediction Goal:")
print(prediction_goal)

Business Problem:
A company wants to predict which customers are likely to purchase a product.

Machine Learning Problem:
This is a classification problem because we want to predict whether the customer will purchase or not.

Prediction Goal:
Predict whether a customer will purchase a product: Yes or No.

In [11]:
# Step 4: Defining Features and Target

# Define the feature columns
# These are the input variables that the model will use to make predictions
feature_columns = [
    "Age",
    "Gender",
    "City",
    "Income",
    "Website_Visits",
    "Previous_Purchases",
    "Membership_Level"
]

# Define X as the feature matrix
# X contains all input columns
X = df[feature_columns]

# Define y as the target variable
# y contains the column we want to predict
y = df["Purchased"]

# Display the first 5 rows of X
print("Features (X):")
display(X.head())

# Display the first 5 values of y
print("Target (y):")
display(y.head())

Features (X):

,Age,Gender,City,Income,Website_Visits,Previous_Purchases,Membership_Level
0,22,Female,Toronto,30000.0,2,0,Basic
1,25,Male,Oshawa,35000.0,3,0,Basic
2,47,Female,Toronto,72000.0,10,3,Gold
3,52,Male,Ajax,85000.0,14,4,Gold
4,46,Female,Whitby,68000.0,9,2,Silver

Target (y):

0     No
1     No
2    Yes
3    Yes
4    Yes
Name: Purchased, dtype: object

In [12]:
# Step 4: Defining Features and Target

# Define the feature columns
# These are the input variables that the model will use to make predictions
feature_columns = [
    "Age",
    "Gender",
    "City",
    "Income",
    "Website_Visits",
    "Previous_Purchases",
    "Membership_Level"
]

# Define X as the feature matrix
# X contains all input columns
X = df[feature_columns]

# Define y as the target variable
# y contains the column we want to predict
y = df["Purchased"]

# Display the first 5 rows of X
print("Features (X):")
display(X.head())

# Display the first 5 values of y
print("Target (y):")
display(y.head())

Features (X):

,Age,Gender,City,Income,Website_Visits,Previous_Purchases,Membership_Level
0,22,Female,Toronto,30000.0,2,0,Basic
1,25,Male,Oshawa,35000.0,3,0,Basic
2,47,Female,Toronto,72000.0,10,3,Gold
3,52,Male,Ajax,85000.0,14,4,Gold
4,46,Female,Whitby,68000.0,9,2,Silver

Target (y):

0     No
1     No
2    Yes
3    Yes
4    Yes
Name: Purchased, dtype: object

In [13]:
# Check the shape of X and y

# X should have rows and feature columns
print("Shape of X:", X.shape)

# y should have only rows
print("Shape of y:", y.shape)

Shape of X: (51, 7)
Shape of y: (51,)

In [14]:
# Step 5: Basic Data Cleaning

# Create a copy of the original dataset before cleaning
# This helps us keep the original data unchanged
df_clean = df.copy()

# Display the number of missing values in each column
# This helps us identify which columns have empty values
print("Missing values before cleaning:")
print(df_clean.isnull().sum())

# Display the number of duplicate rows in the dataset
# Duplicate rows may affect the model training process
print("\nNumber of duplicate rows before cleaning:")
print(df_clean.duplicated().sum())

# Display the data type of each column
# This helps us check whether columns are stored in the correct format
print("\nData types before cleaning:")
print(df_clean.dtypes)

Missing values before cleaning:
Customer_ID           0
Age                   0
Gender                0
City                  1
Income                1
Website_Visits        0
Previous_Purchases    0
Membership_Level      1
Purchased             0
dtype: int64

Number of duplicate rows before cleaning:
1

Data types before cleaning:
Customer_ID             int64
Age                     int64
Gender                 object
City                   object
Income                float64
Website_Visits          int64
Previous_Purchases      int64
Membership_Level       object
Purchased              object
dtype: object

In [15]:
# Fill missing values in the Income column with the median income
# The median is often used because it is less affected by very large or very small values
df_clean["Income"] = df_clean["Income"].fillna(df_clean["Income"].median())

# Fill missing values in the City column with the most frequent city
# mode()[0] returns the most common value in the column
df_clean["City"] = df_clean["City"].fillna(df_clean["City"].mode()[0])

# Fill missing values in the Membership_Level column with the most frequent membership level
# This is useful for categorical columns
df_clean["Membership_Level"] = df_clean["Membership_Level"].fillna(df_clean["Membership_Level"].mode()[0])

# Remove duplicate rows from the dataset
# This keeps only one copy of repeated records
df_clean = df_clean.drop_duplicates()

# Display the dataset after removing duplicates
df_clean.head()

,Customer_ID,Age,Gender,City,Income,Website_Visits,Previous_Purchases,Membership_Level,Purchased
0,1,22,Female,Toronto,30000.0,2,0,Basic,No
1,2,25,Male,Oshawa,35000.0,3,0,Basic,No
2,3,47,Female,Toronto,72000.0,10,3,Gold,Yes
3,4,52,Male,Ajax,85000.0,14,4,Gold,Yes
4,5,46,Female,Whitby,68000.0,9,2,Silver,Yes

In [16]:
# Convert Customer_ID to integer
# Customer_ID is an identifier, not a prediction feature
df_clean["Customer_ID"] = df_clean["Customer_ID"].astype(int)

# Convert Age to integer
# Age should be stored as a numeric whole number
df_clean["Age"] = df_clean["Age"].astype(int)

# Convert Income to float
# Income is numeric and may contain decimal values after cleaning
df_clean["Income"] = df_clean["Income"].astype(float)

# Convert Website_Visits to integer
# Website visits should be numeric
df_clean["Website_Visits"] = df_clean["Website_Visits"].astype(int)

# Convert Previous_Purchases to integer
# Previous purchases should be numeric
df_clean["Previous_Purchases"] = df_clean["Previous_Purchases"].astype(int)

# Convert categorical columns to category type
# This helps us clearly separate categorical variables from numerical variables
df_clean["Gender"] = df_clean["Gender"].astype("category")
df_clean["City"] = df_clean["City"].astype("category")
df_clean["Membership_Level"] = df_clean["Membership_Level"].astype("category")
df_clean["Purchased"] = df_clean["Purchased"].astype("category")

# Display data types after cleaning
print("Data types after cleaning:")
print(df_clean.dtypes)

Data types after cleaning:
Customer_ID              int64
Age                      int64
Gender                category
City                  category
Income                 float64
Website_Visits           int64
Previous_Purchases       int64
Membership_Level      category
Purchased             category
dtype: object

In [17]:
# Check missing values again after cleaning
print("Missing values after cleaning:")
print(df_clean.isnull().sum())

# Check duplicate rows again after cleaning
print("\nNumber of duplicate rows after cleaning:")
print(df_clean.duplicated().sum())

# Display the shape of the cleaned dataset
print("\nShape of cleaned dataset:")
print(df_clean.shape)

# Display the first 5 rows of the cleaned dataset
df_clean.head()

Missing values after cleaning:
Customer_ID           0
Age                   0
Gender                0
City                  0
Income                0
Website_Visits        0
Previous_Purchases    0
Membership_Level      0
Purchased             0
dtype: int64

Number of duplicate rows after cleaning:
0

Shape of cleaned dataset:
(50, 9)

,Customer_ID,Age,Gender,City,Income,Website_Visits,Previous_Purchases,Membership_Level,Purchased
0,1,22,Female,Toronto,30000.0,2,0,Basic,No
1,2,25,Male,Oshawa,35000.0,3,0,Basic,No
2,3,47,Female,Toronto,72000.0,10,3,Gold,Yes
3,4,52,Male,Ajax,85000.0,14,4,Gold,Yes
4,5,46,Female,Whitby,68000.0,9,2,Silver,Yes

In [18]:
# Replace the original dataframe with the cleaned dataframe
# From this point forward, we will use df as the cleaned dataset
df = df_clean.copy()

In [19]:
# Step 6: Preprocessing

# Import ColumnTransformer to apply different preprocessing steps to different columns
from sklearn.compose import ColumnTransformer

# Import OneHotEncoder for categorical variables
# Import StandardScaler for numerical variables
from sklearn.preprocessing import OneHotEncoder, StandardScaler

In [20]:
# Define the feature columns
# These are the input variables that the model will use
feature_columns = [
    "Age",
    "Gender",
    "City",
    "Income",
    "Website_Visits",
    "Previous_Purchases",
    "Membership_Level"
]

In [21]:
# Define X as the feature matrix
# X contains all input variables
X = df[feature_columns]

# Define y as the target variable
# y contains the column we want to predict
y = df["Purchased"]
# Convert the target variable from text labels to numbers
# "No" becomes 0 and "Yes" becomes 1
y = y.map({"No": 0, "Yes": 1})
# Define numerical features
# These columns contain numbers and will be scaled
numerical_features = [
    "Age",
    "Income",
    "Website_Visits",
    "Previous_Purchases"
]

In [22]:
# Define categorical features
# These columns contain text categories and will be encoded
categorical_features = [
    "Gender",
    "City",
    "Membership_Level"
]
# Create a preprocessing object
# StandardScaler will be applied to numerical columns
# OneHotEncoder will be applied to categorical columns
preprocessor = ColumnTransformer(
    transformers=[
        ("num", StandardScaler(), numerical_features),
        ("cat", OneHotEncoder(handle_unknown="ignore"), categorical_features)
    ]
)
# Display the first 5 rows of the feature matrix
print("Features before preprocessing:")

display(X.head())

Features before preprocessing:

,Age,Gender,City,Income,Website_Visits,Previous_Purchases,Membership_Level
0,22,Female,Toronto,30000.0,2,0,Basic
1,25,Male,Oshawa,35000.0,3,0,Basic
2,47,Female,Toronto,72000.0,10,3,Gold
3,52,Male,Ajax,85000.0,14,4,Gold
4,46,Female,Whitby,68000.0,9,2,Silver

In [23]:
# Display the first 5 values of the target variable
print("Target after converting Yes/No to 1/0:")

display(y.head())

Target after converting Yes/No to 1/0:

0    0
1    0
2    1
3    1
4    1
Name: Purchased, dtype: category
Categories (2, int64): [0, 1]